project:
  type: website
  output-dir: docs
website:
  title: "herikevans"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: bi-apple
      - href: about.qmd
        text: About
      - href: dashboard.qmd 
        text: Dashboard
format:
  html:
    theme: lux
    css: styles.css
    toc: true



